### ISSUE TITLE
How does the API pagination work for Employees List? 

### ISSUE THREAD

**Issue by sbk-codes** [merge-api/merge-hris-ruby#36]
I'm using the API `employees_list_with_http_info` which returns `PaginatedEmployeeList`. I can't find instructions to use `_next` and `previous` to get the next set of data?

**Comment by amandamerge** [comment]
Hi @sbk-codes you can find instructions on how to use pagination in our documentation here: https://merge.dev/docs/basics/pagination! Let me know if you have further questions after reviewing.

**Comment by sbk-codes** [comment]
@amandamerge -- That helps, Thanks!
